trigger:
  - master

variables:
  JUICE_SHOP_REPO: 'https://github.com/mile9299/spooky.git'
  DOCKER_PORT: 3000
  # SPECTRAL_DSN: $(SPECTRAL_DSN)

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndDeploy
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.0.0'
        displayName: 'Use Node.js 18.x'

      - checkout: self
        displayName: 'Checkout Repository'
        clean: true

      - script: |
          echo 'Building Docker image...'
          docker build -t spooky -f Dockerfile .
          echo 'Docker image built successfully!'
        displayName: 'Build Docker Image'

      - script: |
          echo 'Deploying application...'
          docker stop spooky || true
          docker rm spooky || true
          container_id=$(docker run -d -P --name spooky spooky)
          docker_host_port=$(docker port $container_id $(DOCKER_PORT) | cut -d ':' -f 2)
          echo "Spooky is running on http://localhost:${docker_host_port}"
        displayName: 'Deploy Application'

      - script: |
          echo 'Build, test, and deployment successful!'
          